"""Shell completion generation for the ``mdb`` command.

Homebrew asks the installed executable to generate completion files. Keeping
the generator in mdb means formulae do not need to duplicate CLI knowledge,
and the drift test in ``tests/test_completions.py`` catches new root options
that have not yet been taught to the completion model.
"""

from __future__ import annotations

import sys


COMMANDS = (
    "watch", "get", "daemon", "oracle", "doctor", "setup", "feed",
    "ddg", "ddg-html", "mojeek", "search", "completion",
)

ROOT_OPTIONS = (
    "-h", "--help", "--start", "--bookmarks", "--reading-list", "--browse",
    "--plain", "--no-center", "--speak", "--speak-out", "--voice",
    "--announce", "--private", "--anonymous", "--wait", "--headed",
    "--fallback-headed", "--backend", "--allow-external-fallback", "--raw",
    "--dump", "--save", "--fixture", "--selftest", "--update-goldens",
    "--width", "--no-pager", "--version",
)


def bash_completion() -> str:
    commands = " ".join(COMMANDS)
    options = " ".join(ROOT_OPTIONS)
    return f"""# bash completion for mdb; generated by `mdb completion bash`
_mdb_complete() {{
    local cur prev
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    case "$prev" in
        --backend)
            COMPREPLY=($(compgen -W "native auto opencli twitter-cli" -- "$cur"))
            return 0
            ;;
        --dump)
            COMPREPLY=($(compgen -W "bundle manifest body" -- "$cur"))
            return 0
            ;;
    esac

    case "${{COMP_WORDS[1]}}" in
        completion)
            COMPREPLY=($(compgen -W "bash zsh" -- "$cur"))
            return 0
            ;;
        watch)
            if [[ $COMP_CWORD -eq 2 ]]; then
                COMPREPLY=($(compgen -W "add rm scan diff log digest ls" -- "$cur"))
                return 0
            fi
            ;;
        daemon)
            if [[ $COMP_CWORD -eq 2 ]]; then
                COMPREPLY=($(compgen -W "start stop status run" -- "$cur"))
                return 0
            fi
            ;;
        setup)
            if [[ $COMP_CWORD -eq 2 ]]; then
                COMPREPLY=($(compgen -W "backends" -- "$cur"))
                return 0
            fi
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "{options}" -- "$cur"))
    elif [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "{commands}" -- "$cur"))
    fi
}}
complete -F _mdb_complete mdb
"""


def zsh_completion() -> str:
    commands = " ".join(COMMANDS)
    options = " ".join(ROOT_OPTIONS)
    return f"""#compdef mdb
# zsh completion for mdb; generated by `mdb completion zsh`
_mdb() {{
    local cur="${{words[CURRENT]}}"
    local prev="${{words[CURRENT-1]}}"
    local -a commands options
    commands=({commands})
    options=({options})

    case "$prev" in
        --backend)
            _values 'backend' native auto opencli twitter-cli
            return
            ;;
        --dump)
            _values 'pipeline stage' bundle manifest body
            return
            ;;
    esac

    case "${{words[2]}}" in
        completion)
            _values 'shell' bash zsh
            return
            ;;
        watch)
            if (( CURRENT == 3 )); then
                _values 'watch action' add rm scan diff log digest ls
                return
            fi
            ;;
        daemon)
            if (( CURRENT == 3 )); then
                _values 'daemon action' start stop status run
                return
            fi
            ;;
        setup)
            if (( CURRENT == 3 )); then
                _values 'setup target' backends
                return
            fi
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        _describe 'option' options
    elif (( CURRENT == 2 )); then
        _describe 'command' commands
    fi
}}
compdef _mdb mdb
"""


def generate(shell: str) -> str:
    if shell == "bash":
        return bash_completion()
    if shell == "zsh":
        return zsh_completion()
    raise ValueError(f"unsupported shell: {shell}")


def completion_cli(argv: list[str]) -> int:
    if len(argv) != 1 or argv[0] not in ("bash", "zsh"):
        print("usage: mdb completion [bash|zsh]", file=sys.stderr)
        return 2
    print(generate(argv[0]), end="")
    return 0
